### PR TITLE
chore(requirements.txt): sorted in alphabetical order

### PR DESCRIPTION
**Pull request by jingpengw**
as the number of required packages grows, it is hard to find duplicates or inconsistent package version.

### CODE REVIEW

**Comment by william-silversmith** [comment]
This looks good jingpeng, would you mind rewording the commit message to say: `chore(requirements.txt): sorted in alphabetical order`?

**Comment by jingpengw** [comment]
yeah, but I'm not sure how to do it.

**Comment by william-silversmith** [comment]
Super easy!

git commit --amend
git push -f

You can also be more adventurous and try out:

git rebase -i master

**Comment by jingpengw** [comment]
nice, just changed the commit message!

**Comment by william-silversmith** [comment]
Just waiting for travis now. Tho we've been having a lot of problems with it :P

**Comment by william-silversmith** [comment]
Looks like all the unit tests passed both travis tests. We need to get to the bottom of these test failures.

**Pull request merged**
