### PR TITLE
google-cloud 0.26 only works with google-cloud-storage version < 1.3.0

### PR DESCRIPTION
**Pull request by jingpengw**
see this issue:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3736

if the version is not correct, will get error:
```
File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 502, in download_as_string
    self.download_to_file(string_buffer, client=client)
  File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 464, in download_to_file
    self._do_download(transport, file_obj, download_url, headers)
  File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 418, in _do_download
    download.consume(transport)
  File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 96, in consume
    transport, method, url, **request_kwargs)
  File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/resumable_media/requests/_helpers.py", line 101, in http_request
    func, RequestsMixin._get_status_code, retry_strategy)
  File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google/resumable_media/_helpers.py", line 146, in wait_and_retry
    response = func()
  File "/Users/jpwu/libs/anaconda2/lib/python2.7/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
TypeError: request() got an unexpected keyword argument 'data'
```

### CODE REVIEW

**Comment by jingpengw** [comment]
@william-silversmith can we merge? this is a very tiny change.

**Comment by william-silversmith** [comment]
I think installing with pip made this work on your machine while we were at the conference. I'm a bit skeptical of over specifying the internal contents of google cloud storage unless there's no other way. If you still think this is important, we can merge it.

**Comment by jingpengw** [comment]
I retried on my workstation, only this specific version works, otherwise we'll get error.
```

Exception in task_execution.py running at jwu-meshing-3151180608-s3678. Traceback (most recent call last): File "/root/python/neuroglancer/pipeline/task_execution.py", line 25, in <module> task.execute() File "neuroglancer/pipeline/tasks.py", line 166, in execute self._volume = CloudVolume(self.layer_path, self.mip, bounded=False) File "neuroglancer/pipeline/volumes/cloudvolume.py", line 80, in __init__ self.refreshInfo() File "neuroglancer/pipeline/volumes/cloudvolume.py", line 121, in refreshInfo infojson = self._storage.get_file('info') File "neuroglancer/pipeline/storage.py", line 125, in get_file content, decompress = self._interface.get_file(file_path) File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 87, in wrapped_f return r.call(f, *args, **kw) File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 235, in call do = self.iter(result=result, exc_info=exc_info) File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 205, in iter raise RetryError(fut).reraise() File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 284, in reraise raise self.last_attempt.result() File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result return self.__get_result() File "/usr/local/lib/python2.7/site-packages/tenacity/__init__.py", line 238, in call result = fn(*args, **kwargs) File "neuroglancer/pipeline/storage.py", line 420, in get_file return blob.download_as_string(), False File "/usr/local/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 502, in download_as_string self.download_to_file(string_buffer, client=client) File "/usr/local/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 464, in download_to_file self._do_download(transport, file_obj, download_url, headers) File "/usr/local/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 418, in _do_download download.consume(transport) File "/usr/local/lib/python2.7/site-packages/google/resumable_media/requests/download.py", line 96, in consume transport, method, url, **request_kwargs) File "/usr/local/lib/python2.7/site-packages/google/resumable_media/requests/_helpers.py", line 101, in http_request func, RequestsMixin._get_status_code, retry_strategy) File "/usr/local/lib/python2.7/site-packages/google/resumable_media/_helpers.py", line 146, in wait_and_retry response = func() File "/usr/local/lib/python2.7/site-packages/google_auth_httplib2.py", line 198, in request uri, method, body=body, headers=request_headers, **kwargs) TypeError: request() got an unexpected keyword argument 'data'
```

**Comment by jingpengw** [comment]
the build works, but the image is not usable.

**Pull request merged**
