### PR TITLE
add rough precision mode for find path tool

### PR DESCRIPTION
**Pull request by manuel-castro**
Pulling this missing functionality from the now deprecated akhilesh-graphene-sharded branch

### CODE REVIEW

**Review by ogewan — CHANGES_REQUESTED** [review]
I'm not very familiar with this tool. Would it be possible to change the functionality so that a path is redrawn when I toggle precision mode?

The control seems to work, but from what I have tested it doesn't seem to have change when using precision. That being said, it would be much easier to test if you added that redraw so that I don't need to reselect source and sink when switching.

**Comment by sdorkenw** [comment]
@manuel-castro what is the latest on this PR?

**Comment by manuel-castro** [comment]
Sorry @sdorkenw, I missed your question until today. The find_path endpoint didn't work for me last week and today when I tested. However, today I realized it works on Minnie, so I will move forward with making the change @ogewan suggested.

**Review by ogewan — CHANGES_REQUESTED** [review]
[redacted]

**Comment by manuel-castro** [comment]
That's an issue with the Flywire ChunkedGraph. If you try another ChunkedGraph, such as Minnie, you can see the feature working.

**Review by ogewan — APPROVED** [review]
LGTM

**Pull request merged**
