### PR TITLE
Graphene and Precomputed Volumes able to decode Draco encoded meshes

### PR DESCRIPTION
**Pull request by manuel-castro**
They will attempt to run the included Draco WebAssembly decoder on a FragmentChunk. If that fails, they will fall back to the old FragmentChunk decoder.

### CODE REVIEW

**Comment by william-silversmith** [comment]
Is it possible to use the content type attribute to determine which decoder
to use?

**Comment by nkemnitz** [comment]
> Is it possible to use the content type attribute to determine which decoder to use?

The `content-type` is risky - we already ran into situations were copying data from one bucket to another did not set the content-type correctly.

Ideally, the file itself contains all the information required by the decoder. For example, the draco file format use `DRACO` as magic number, the Stanford file format uses `ply`... The problem currently is that we need to stay backward compatible to the custom binary mesh format, which has no identifier whatsoever. In that sense, checking for proper file formats first, and then falling back to the legacy format is the safest we can do here.

**Comment by william-silversmith** [comment]
Perhaps this is OT and we should take it off thread, but under what
circumstances did the content-type get lost? One thing that concerns me is
that when using magic numbers with numerous non-magic numbered meshes, what
is the probability of the same bytes appearing by accident? Maybe it's
unlikely because the initial 4 bytes of the mesh format describe the number
of vertices, so the risk would only be present if there were "p" = 112 x
2^24 or about 1.8B vertices for ply files, and for draco, it would be 1.6B+.

**Comment by william-silversmith** [comment]
👋👋👋

**Pull request merged**
