### PR TITLE
refactor(tasks.py): reduce dependency

### PR DESCRIPTION
**Pull request by jingpengw**
put the dependency packages to tasks.

### CODE REVIEW

**Comment by jingpengw** [comment]
@william-silversmith I just added a few comment lines. not sure it is what you expected or not.

**Comment by william-silversmith** [comment]
Hmm, I meant more like write why we are moving these imports in particular and not others. I can see that we're importing intern from the lines themselves.

**Comment by william-silversmith** [comment]
@jingpengw Would you mind rebasing this on master? I think it will fix the travis problem.

**Comment by jingpengw** [comment]
@william-silversmith there are a bunch of conflicts. you should rebase your `quantizedaffinities` first?

**Comment by william-silversmith** [comment]
oh my bad. you're right

**Comment by jingpengw** [comment]
rebased to your updated `quantizedaffinities` branch

**Comment by tartavull** [comment]
maybe related
https://stackoverflow.com/questions/563022/whats-python-good-practice-for-importing-and-offering-optional-features
https://softwareengineering.stackexchange.com/questions/262697/is-it-safe-to-catch-importerror-when-trying-to-import-optional-modules

**Comment by tartavull** [comment]
@jingpengw what shall I do with this?

**Comment by jingpengw** [comment]
cloud volume was split out, I think we can close this.

**Pull request closed without merging**
