### PR TITLE
 feat(Storage): added retry logic recommended on AWS blog

### PR DESCRIPTION
**Pull request by william-silversmith**
See #91 

I added the functionality recommended here by [AWS]( https://www.awsarchitectureblog.com/2015/03/backoff.html) to the tenacity library in this PR: 

https://github.com/jd/tenacity/pull/70

### CODE REVIEW

**Comment by william-silversmith** [comment]
The tricky thing is that it's really only 404 errors that are legit, everything else is a network error and they are not all IOErrors. Some of them are SSLErrors, some are DNS errors, and they all change based on the library used (boto vs gcloud). Maybe we should just make a narrow exception for 404s?

**Comment by william-silversmith** [comment]
Hmm, I do think you're right and I want to add this 404 functionality, but I don't have time at the moment. It was causing me some problems before, but it isn't now. Could we make this an issue and I'll resolve it next time it's a problem? An initial attempt revealed that there might be an issue with reraising the original exceptions.

**Comment by william-silversmith** [comment]
Rebased

**Comment by wongwill86** [comment]
`retry=retry_if_exception_type(IOError)` was only an example with IOErrors. The point is there are errors that should be retried and many that we shouldn't. See [AWSS3.jl](https://github.com/samoconnor/AWSS3.jl/blob/master/src/AWSS3.jl#L108). We might need to wrap the exceptions inside the interfaces to delineate between retry-able errors and non-retry-able errors so we can handle it at the Facade level appropriately
see:
http://docs.aws.amazon.com/AmazonS3/latest/dev/ErrorBestPractices.html
http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

This should definitely be a requirement for this feature because inappropriate retries will waste a time. It will become an issue trying to debug in the future as well. 

I think it's ok to merge if it's blocking something you need to run right now. if not, i would prefer to include it in this PR before it'll drop off the radar. Waiting up to 7 minutes(?) because i put in the wrong file name seems terribly inefficient especially for development purposes.

**Comment by william-silversmith** [comment]
Fwiw, 7 retries means:

.25 + 0.5 + 1 + 2 +4 + 8 + 16 + 30 = 61.75 seconds of non-request waiting on average and 123.5 seconds maximum (~1 min and ~2 min respectively).

**Comment by tartavull** [comment]
@william-silversmith  Revisit this and tell us when it's ready

**Comment by william-silversmith** [comment]
On closer inspection, I forgot that the reason why the 404s weren't a problem is because we were returning "None" instead, so it never got raised and it avoided the problem. If you think that's the wrong approach, let's discuss, but I think that moots the objection.

**Comment by wongwill86** [comment]
I think we're talking about the same thing but attacking the problem from
different ends. What I'm suggesting isn't to blacklist 404 from retrying,
but to whitelist known retry conditions. Again, here is (AWS.jl)[github.com/
samoconnor/AWSS3.jl/blob/master/src/AWSS3.jl#L137] and (Amazon 503)[
docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html]. (should
probably retry on timeouts as well...)
The rationale is that there may be infinite error conditions and codes that
we don't know how to handle and we're going to waste our time retrying but
there are a subset that we definitely know we should retry.

**Comment by william-silversmith** [comment]
Hmm... I guess I don't really put much of a price on retrying, I care more that things that should work do work and if they are constantly failing I'll notice that when I check the logs. I think making a whitelist is potentially more costly in terms of queue reliability since I've seen so many different kinds of errors that were mainly network/DNS related (SSLError, Not Found, DNS, and others) and very few that weren't in practice. I wanted blanket coverage to protect against these things even if it was difficult to find a way to reference the error in code. I had trouble finding the originating library that contained the definition of a kind of SSLError iirc, it might have been embedded in Cython. Nonetheless, I wanted to retry.

**Comment by wongwill86** [comment]
Approving this with concerns since we can always fix this later.

To summarize, I believe the correct and safe thing to do is to identify the known retry conditions and only retry when we know it is safe (i.e. whitelist known errors for retry):
1. One task that requests one cutout may require over a thousand requests (1kx1kx300 volumes split into 64x64x64). Unnecessary errors can cascade to cause even more network congestion (7x retries of thousand+ requests) and may cause use to waste of lot of time (especially on on developer side). 
2. Identifying the errors forces us to investigate and understand the error. This will help us identify any misconfigured items in our pipeline so we can avoid 1.

To this, @william-silversmith has responded that we should just blanket retry everything because:
1. retrying one request should only take 1 minute maximum and retry costs are not important enough to be considered.
2. There number of errors that can occur are too many to enumerate beyond 503 and timeout, stating that at our scale, AWS and GCP is not stable enough to handle that many requests without random unaccountable errors. Such errors he has seen have been dns resolution errors (which he solved by scaling out kube-dns), ssl handshake errors, host unreachable errors, and threading errors.

**Pull request merged**
