### PR TITLE
Seun Save State Mac Patch

### PR DESCRIPTION
**Pull request by ogewan**
This patch fixes all problems. All of them ever. Every problem that has existed, exists, and will exist. This solves them all. Pack it up, we are done. Shows over folks.

### CODE REVIEW

**Comment by ogewan** [comment]
Changes:
Unshared state warning (loading when button is yellow) is now dismissable via "dismiss" button
It can also be disabled/renabled via User Prefrences

Save State rewrite
Every session now has a unique session ID. Every state tab is stored in an entry in localStorage. If two or more tabs are making changes to the same state,

**Comment by nkemnitz** [comment]
The following use case does not work as expected:
1. copy an existing `local ID` URL (tab A) to a new tab (tab B)
2. change the view/state in tab B
3. refresh tab A

Current behavior: tab A will switch to the same state as tab B, meaning we lose tab A state
Expected: I think the creation of tab B should have already led to a new unique ID, so that it is no longer coupled to tab A?

**Comment by ogewan** [comment]
> Expected: I think the creation of tab B should have already led to a new unique ID, so that it is no longer coupled to tab A?

The mechanism to prevent duplicate is reactionary. The expectation is that the most recent session to change the tab is is the new owner continuing on from the last session. Which is the case for simply reloading.

When a change is made by an "older" session, i.e a session that made a change before the most current session, that session knows its in conflict and branches, since there is no way to alert the other session. 

The session instance is renewed on page load.

The problem with this is that the session needs to check localStorage to make this change. A possible solution is to check localStorage on focus, but I'm not sure if this will catch a reload. Additionally, if you duplicate and close and reopen the browser the state will be identical as well.

This is a compromise between completely tying states to local id, and making a new local id per individual session.

**Comment by ogewan** [comment]
So it turns out the on focus thing works better than I expected. There is still the limitation of not being able to detect a duplicated tab, because it cant distinguish between duplication and reloading, but if you switch back to the original tab it will change its local_id. This is because the new tab register's itself in the state history and the on focus handler checks for new entries in the state history to determine if needs to change local id.

You can't do this in reverse because an on blur command would fire and subsequently check before the new tab has registered itself. When directly copying and pasting the link versus duplicating, its even worse because the blur event will fire well before the new tab registers.

I think the is the best we can get without outright threading or something like that because the only use case it doesn't cover is maintaining different states on the same local ID if the browser has restarted.

**Pull request merged**
